"""empty message

Revision ID: 1c320283a825
Revises: d37bf140590f
Create Date: 2022-03-10 14:38:29.936381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c320283a825'
down_revision = 'd37bf140590f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
